import { Share, Platform } from 'react-native';
import { GeneratedSet } from '@/types/lottery';
import { GAME_CONFIGS } from '@/constants/games';

export async function shareNumbers(result: GeneratedSet, confidence?: number): Promise<boolean> {
  const config = GAME_CONFIGS[result.game];
  const numbersStr = result.numbers.join(' \u2022 ');
  const conf = confidence ?? result.prediction.confidence;

  const message = `\u{1F3AF} AI CONFIDENCE: ${conf}%\n\nNumbers:\n${numbersStr}\n${config.bonusName}: ${result.bonusNumber}\n\n\u{1F9E0} Generated by LottoMind AI\n${config.name} \u2022 ${result.strategy.charAt(0).toUpperCase() + result.strategy.slice(1)} strategy\n\n\u{1F525} Get your own AI picks \u2192 lottomind.ai`;

  try {
    const shareResult = await Share.share(
      Platform.OS === 'ios'
        ? { message }
        : { message, title: 'My LottoMind AI Picks' }
    );
    console.log('[Share] Result:', shareResult);
    return shareResult.action === Share.sharedAction;
  } catch (error) {
    console.log('[Share] Error:', error);
    return false;
  }
}

export async function shareReferral(code: string): Promise<boolean> {
  const message = `\u{1F525} I'm using LottoMind AI to get smarter lottery picks!\n\nUse my code ${code} to get 5 free credits.\n\n\u{1F3B0} AI-powered number generation\n\u{1F9E0} Dream interpretation\n\u{1F4CA} Live draw analysis\n\n\u{1F449} Download now \u2192 lottomind.ai`;

  try {
    const result = await Share.share(
      Platform.OS === 'ios'
        ? { message }
        : { message, title: 'Join LottoMind AI' }
    );
    return result.action === Share.sharedAction;
  } catch (error) {
    console.log('[Share] Referral error:', error);
    return false;
  }
}

export async function shareDailyPick(numbers: number[], bonus: number, confidence: number, gameName: string): Promise<boolean> {
  const numbersStr = numbers.join(' \u2022 ');
  const message = `\u{1F6A8} TODAY'S AI PICK (${confidence}% Confidence)\n\n${numbersStr} + ${bonus}\n\n\u26A1 Only available for 24 hours\n\u{1F9E0} Generated by LottoMind AI \u2022 ${gameName}\n\n\u{1F449} Get yours \u2192 lottomind.ai`;

  try {
    const result = await Share.share(
      Platform.OS === 'ios'
        ? { message }
        : { message, title: "Today's LottoMind AI Pick" }
    );
    return result.action === Share.sharedAction;
  } catch (error) {
    console.log('[Share] Daily pick error:', error);
    return false;
  }
}
