export const ARCADE_CONFIG = {
  world: {
    viewportWidth: 960,
    viewportHeight: 540,
    touchLookAhead: 120,
  },
  player: {
    width: 84,
    height: 96,
    spawnX: 120,
    maxRunSpeed: 392,
    acceleration: 3120,
    airAcceleration: 2240,
    friction: 2860,
    crouchSpeed: 122,
    gravity: 2380,
    jumpVelocity: 930,
    climbSpeed: 238,
    coyoteSeconds: 0.1,
    jumpBufferSeconds: 0.14,
    variableJumpCutoff: 520,
    hurtKickX: 250,
    hurtKickY: 560,
    invulnerableSeconds: 1.1,
    jackpotPowerSeconds: 6,
    slowSeconds: 1.7,
    slowMultiplier: 0.58,
    jackpotSpeedMultiplier: 1.14,
  },
  boss: {
    width: 300,
    height: 210,
    baseSpeed: 120,
    maxSpeed: 254,
    minGap: 164,
    maxGap: 372,
    pressureRampSeconds: 82,
    catchDistance: 26,
  },
  camera: {
    leadFactor: 0.28,
    smoothing: 7,
  },
  hazards: {
    goldPuddleMode: "boost",
    goldPuddleBoostX: 455,
    goldPuddleBoostY: 760,
    goldPuddleProtectionSeconds: 0.3,
    scorpionTravelDistance: 46,
    scorpionMoveSpeed: 2.2,
    bossPressurePulseThresholds: [0.58, 0.82],
  },
  pickups: {
    gemScore: 100,
    ringScore: 500,
    treasureScore: 1000,
  },
  rewards: {
    stageClearTimeBonusPerSecond: 40,
    stageClearLifeBonus: 250,
  },
  particles: {
    pickupBurst: 8,
    hurtBurst: 12,
    powerBurst: 14,
  },
} as const;
