export const STATE_GAME_DISPLAY_NAMES: Record<string, { name: string; color: string }> = {
  powerball: { name: 'Powerball', color: '#E74C3C' },
  megamillions: { name: 'Mega Millions', color: '#3498DB' },
  lottoTexas: { name: 'Lotto Texas', color: '#F5A623' },
  pick3: { name: 'Pick 3', color: '#9B59B6' },
  daily4: { name: 'Daily 4', color: '#1ABC9C' },
  cashFive: { name: 'Cash Five', color: '#2ECC71' },
  texasTwoStep: { name: 'Texas Two Step', color: '#E67E22' },
  superLottoPlus: { name: 'SuperLotto Plus', color: '#FFD700' },
  fantasy5: { name: 'Fantasy 5', color: '#27AE60' },
  daily3: { name: 'Daily 3', color: '#8E44AD' },
  lotto: { name: 'Lotto', color: '#D4AF37' },
  pick4: { name: 'Pick 4', color: '#16A085' },
  cash4Life: { name: 'Cash4Life', color: '#2ECC71' },
  lotto47: { name: 'Lotto 47', color: '#F39C12' },
  keno: { name: 'Keno', color: '#E74C3C' },
  luckyForLife: { name: 'Lucky for Life', color: '#27AE60' },
  floridaLotto: { name: 'Florida Lotto', color: '#F5A623' },
  luckyDayLotto: { name: 'Lucky Day Lotto', color: '#F1C40F' },
  cash3: { name: 'Cash 3', color: '#9B59B6' },
  cash4: { name: 'Cash 4', color: '#16A085' },
  georgiaLottery: { name: 'Georgia Lottery', color: '#E74C3C' },
  cash5: { name: 'Cash 5', color: '#2ECC71' },
  pick2: { name: 'Pick 2', color: '#8E44AD' },
  match6: { name: 'Match 6', color: '#3498DB' },
  classicLotto: { name: 'Classic Lotto', color: '#F5A623' },
  rollingCash5: { name: 'Rolling Cash 5', color: '#27AE60' },
  jerseyCash5: { name: 'Jersey Cash 5', color: '#2ECC71' },
  palmettoCash5: { name: 'Palmetto Cash 5', color: '#27AE60' },
  oregonMegabucks: { name: 'Oregon Megabucks', color: '#2ECC71' },
  winForLife: { name: 'Win for Life', color: '#F1C40F' },
  ctLotto: { name: 'CT Lotto!', color: '#E74C3C' },
  play3: { name: 'Play 3', color: '#9B59B6' },
  play4: { name: 'Play 4', color: '#16A085' },
  lottoAmerica: { name: 'Lotto America', color: '#3498DB' },
  tennesseeCash: { name: 'Tennessee Cash', color: '#F5A623' },
  showMeCash: { name: 'Show Me Cash', color: '#E67E22' },
  hit5: { name: 'Hit 5', color: '#2ECC71' },
  match4: { name: 'Match 4', color: '#16A085' },
  coloradoLottoPlus: { name: 'Colorado Lotto+', color: '#3498DB' },
  thePick: { name: 'The Pick', color: '#E74C3C' },
  tripleTwist: { name: 'Triple Twist', color: '#9B59B6' },
  gopher5: { name: 'Gopher 5', color: '#27AE60' },
  northstarCash: { name: 'Northstar Cash', color: '#F5A623' },
  superCash: { name: 'SuperCash!', color: '#2ECC71' },
  badger5: { name: 'Badger 5', color: '#E74C3C' },
  easy5: { name: 'Easy 5', color: '#27AE60' },
  multiMatch: { name: 'Multi-Match', color: '#3498DB' },
  bonusMatch5: { name: 'Bonus Match 5', color: '#F5A623' },
  cashBall: { name: 'Cash Ball', color: '#E74C3C' },
  fiveCardCash: { name: '5 Card Cash', color: '#9B59B6' },
  massCash: { name: 'Mass Cash', color: '#2ECC71' },
  numbersGame: { name: 'Numbers Game', color: '#16A085' },
  megabucks: { name: 'Megabucks', color: '#F5A623' },
  hoosierLotto: { name: 'Hoosier Lotto', color: '#E74C3C' },
  roadrunnerCash: { name: 'Roadrunner Cash', color: '#F39C12' },
  triStateMegabucks: { name: 'Tri-State Megabucks', color: '#3498DB' },
  wildMoney: { name: 'Wild Money', color: '#2ECC71' },
  theNumbers: { name: 'The Numbers', color: '#9B59B6' },
  multiWinLotto: { name: 'Multi-Win Lotto', color: '#F5A623' },
  dc3: { name: 'DC-3', color: '#9B59B6' },
  dc4: { name: 'DC-4', color: '#16A085' },
  dc5: { name: 'DC-5', color: '#2ECC71' },
  cash25: { name: 'Cash 25', color: '#F5A623' },
  dakotaCash: { name: 'Dakota Cash', color: '#E74C3C' },
  wildCard2: { name: 'Wild Card 2', color: '#9B59B6' },
  montanaCash: { name: 'Montana Cash', color: '#27AE60' },
  hotLotto: { name: 'Hot Lotto', color: '#E74C3C' },
  naturalStateJackpot: { name: 'Natural State Jackpot', color: '#2ECC71' },
  superKansasCash: { name: 'Super Kansas Cash', color: '#F5A623' },
  twoByTwo: { name: '2by2', color: '#E67E22' },
  idahoCash: { name: 'Idaho Cash', color: '#27AE60' },
  weeklyGrand: { name: 'Weekly Grand', color: '#F1C40F' },
  pick5: { name: 'Pick 5', color: '#3498DB' },
  myDay: { name: 'MyDaY', color: '#9B59B6' },
};

export function getGameDisplayName(gameId: string): string {
  return STATE_GAME_DISPLAY_NAMES[gameId]?.name ?? gameId;
}

export function getGameColor(gameId: string): string {
  return STATE_GAME_DISPLAY_NAMES[gameId]?.color ?? '#D4AF37';
}
